/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using OutSystems.HubEdition.DatabaseProvider.DB2LUW.DatabaseObjects;
using OutSystems.HubEdition.DatabaseProvider.DB2LUW.DMLService;
using OutSystems.HubEdition.DatabaseProvider.DB2LUW.ExecutionService;
using OutSystems.HubEdition.DatabaseProvider.DB2LUW.IntrospectionService;
using OutSystems.HubEdition.DatabaseProvider.DB2LUW.TransactionService;
using OutSystems.HubEdition.Extensibility.Data;
using OutSystems.HubEdition.Extensibility.Data.ConfigurationService;
using OutSystems.HubEdition.Extensibility.Data.DatabaseObjects;
using OutSystems.HubEdition.Extensibility.Data.DMLService;
using OutSystems.HubEdition.Extensibility.Data.ExecutionService;
using OutSystems.HubEdition.Extensibility.Data.IntrospectionService;
using OutSystems.HubEdition.Extensibility.Data.TransactionService;
using OutSystems.RuntimeCommon.ObfuscationProperties;

namespace OutSystems.HubEdition.DatabaseProvider.DB2LUW {

    [DoNotObfuscateType]
    internal class DB2LUWDatabaseServices : IDatabaseServices {
        private readonly IRuntimeDatabaseConfiguration configuration;
        private readonly IDatabaseObjectFactory objectFactory;
        private readonly ITransactionService transactionService;
        private readonly IExecutionService executionService;
        private readonly IDMLService dmlService;
        private readonly IIntrospectionService introspectionService;

        public DB2LUWDatabaseServices(IRuntimeDatabaseConfiguration databaseConfiguration) {
            configuration = databaseConfiguration;
            objectFactory = new DB2LUWDatabaseObjectFactory(this);
            transactionService = new DB2LUWTransactionService(this);
            executionService = new DB2LUWExecutionService(this);
            dmlService = new DB2LUWDMLService(this);
            introspectionService = new DB2LUWIntrospectionService(this);
        }
        public IDatabaseObjectFactory ObjectFactory { get { return objectFactory; } }
        public ITransactionService TransactionService { get { return transactionService; } }
        public IExecutionService ExecutionService { get { return executionService; } }
        public IDMLService DMLService { get { return dmlService; } }
        public IIntrospectionService IntrospectionService { get { return introspectionService; } }
        public IRuntimeDatabaseConfiguration DatabaseConfiguration { get { return configuration; } }

    }
}
