/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using OutSystems.HubEdition.Extensibility.Data;
using OutSystems.HubEdition.Extensibility.Data.DatabaseObjects;

namespace OutSystems.HubEdition.DatabaseProvider.DB2LUW.DatabaseObjects {
    public class DB2LUWTableSourceInfo : BaseTableSourceInfo {

        public DB2LUWTableSourceInfo(IDatabaseServices databaseServices, DB2LUWDatabaseInfo database, string name, string qualifiedName)
            : base(databaseServices, database, name, qualifiedName) { }

        public new DB2LUWDatabaseInfo Database
        {
            get { return (DB2LUWDatabaseInfo)base.Database; }
        }
    }
}
